export const ErrorCode = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',

  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  CSRF_INVALID: 'CSRF_INVALID',

  FORBIDDEN: 'FORBIDDEN',

  RATE_LIMITED: 'RATE_LIMITED',

  EMAIL_TAKEN: 'EMAIL_TAKEN',
  ACCOUNT_DELETED: 'ACCOUNT_DELETED',
  PLAYLIST_NOT_FOUND: 'PLAYLIST_NOT_FOUND',
  TRACK_NOT_FOUND: 'TRACK_NOT_FOUND',

  ITUNES_UNAVAILABLE: 'ITUNES_UNAVAILABLE',
  PREVIEW_NOT_AVAILABLE: 'PREVIEW_NOT_AVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

const ERROR_CODE_VALUES = new Set<string>(Object.values(ErrorCode));

export function isErrorCode(value: unknown): value is ErrorCode {
  return typeof value === 'string' && ERROR_CODE_VALUES.has(value);
}
