export const SEED_USERS = [
  { email: 'admin@statify.local', displayName: 'Statify Admin', role: 'admin' as const },
  { email: 'alex@statify.local', displayName: 'Alex', role: 'user' as const },
  { email: 'jordan@statify.local', displayName: 'Jordan', role: 'user' as const },
  { email: 'sam@statify.local', displayName: 'Sam', role: 'user' as const },
  { email: 'riley@statify.local', displayName: 'Riley', role: 'user' as const },
];

export const SEED_USER_PASSWORD = 'statify123';

export const ARTIST_ADJECTIVES = [
  'Neon',
  'Velvet',
  'Echo',
  'Lunar',
  'Midnight',
  'Crystal',
  'Silver',
  'Ember',
  'Glass',
  'Wild',
  'Quiet',
  'Burning',
  'Hollow',
  'Open',
  'Distant',
  'Iron',
  'Paper',
  'Marble',
  'Northern',
  'Western',
];

export const ARTIST_NOUNS = [
  'Foxes',
  'Wolves',
  'Tides',
  'Cities',
  'Mountains',
  'Lights',
  'Rivers',
  'Mirrors',
  'Engines',
  'Gardens',
  'Stations',
  'Ravens',
  'Owls',
  'Comets',
  'Atlas',
  'Harbours',
  'Towers',
  'Avenues',
  'Letters',
  'Chambers',
];

export const ALBUM_WORDS = [
  'Horizon',
  'Patterns',
  'Lights',
  'Currents',
  'Drift',
  'Constellations',
  'Static',
  'Glow',
  'Frames',
  'Volumes',
  'Pages',
  'Reflections',
  'Halos',
  'Shapes',
  'Signals',
  'Migrations',
  'Phases',
  'Orbits',
];

export const TRACK_WORDS = [
  'Daybreak',
  'Underline',
  'Slow Burn',
  'In Motion',
  'Soft Edges',
  'Light Year',
  'Open Sky',
  'Half Light',
  'Field Notes',
  'Long Way',
  'After Hours',
  'Cold Run',
  'Bright Sound',
  'Old Maps',
  'Paper Crown',
  'Last Train',
  'Quiet Storm',
  'Glass House',
  'Even Tide',
  'Outer Bands',
];

export const PLAYLIST_THEMES = [
  'Late drive',
  'Sunday morning',
  'Focus deep',
  'Workout boost',
  'Cabin weekend',
  'Coffee shop',
  'Long flight',
  'Trail run',
  'Slow cooking',
  'Friday night',
  'Quiet study',
  'Open road',
];
